# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-19 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='pword',
        ),
    ]
