# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-20 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Authors_app', '0002_author_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='Book_Authors_app.Book'),
        ),
    ]
