# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-18 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas', '0002_auto_20171018_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='dojo_id',
            new_name='dojo',
        ),
    ]
