# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-19 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0002_auto_20170920_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='Description'),
            preserve_default=False,
        ),
    ]
